### ISSUE TITLE
Artificial Neural Network Based Multi-Objective Rule Selection Dispatcher for Re-Entrant Multiple-Chip Product Assembly Line

### ISSUE THREAD

**Issue by koptimizer** [KGJsGit/my_PaperList#1]
## :clipboard: 논문의 정보를 알려주세요.
- Artificial Neural Network Based Multi-Objective Rule Selection Dispatcher for Re-Entrant Multiple-Chip Product Assembly Line
- J. Huh, J. Park
- 2019-02-28

## :page_with_curl: Abstract(본문)
> Recently, the semiconductor manufacturers have focused on the production of multiple chip products (MCPs) to achieve high capacities while preserving compactness. As the number of chips to be stacked increases, a re-entrant flow that repeats die attach and wire bonding assembly stages in MCP production is generated, which causes increased flow time and decreased resource utilization. In this paper, we propose a rule selection dispatcher (RSD) based on an artificial neural network, which reduces the flow time and increases the resource utilization. RSD learns the preferences of each dispatching rule according to assembly line data generated by a simulator. Then the proposed dispatcher performs lot dispatching decisions by selecting one of the dispatching rules. The experiments showed that the proposed dispatcher outperformed the existing methods in terms of the performance and computation time.

## :mag_right: 어떤 논문인지 소개해주세요.
- 다중칩 공정은 집적도에 따른 재유입흐름의 증가로 가동률이 하락하고 흐름시간이 증가합니다.
- 이를 원활히 하고자 조립라인 기반의 시뮬레이션으로 만든 데이터를 학습하여 실시간으로 라인의 상황을 고려해 디스패칭 룰을 선택하는 ANN기반 RSD(Rule Selection Dispatcher)를 제안합니다.

## :key: 핵심 키워드를 적어주세요.
- re-entrant manufacturing lines
- dispatching rules
- artificial neural network

## :paperclip: URL
[http://www.ki-it.com/xml/18418/18418.pdf](http://www.ki-it.com/xml/18418/18418.pdf)

**Comment by koptimizer** [comment]
## :bulb: 방법은 무엇입니까?
1. 라인의 정보를 시뮬레이터에 설정하고 시뮬레이션 하여 학습할 시뮬레이션로그(데이터)를 만듭니다.
2. 만들어진 데이터를 학습하여 디스패쳐 모델을 만듭니다.
3. 의사결정 시점이 왔을 때, 공정의 상황을 기반으로 최적의 디스패치 룰을 선택해서 해당 로트가 할당될 설비에 적용합니다.

## :chart_with_upwards_trend: 실험과 그 결과는 어떻습니까?
- 실험
  - 해당 RSD의 성능을 검증하기 위해 설비 수, 잡 유형 수, 평균 공정 수가 서로 다른 네 공정라인 모형을 설정하였고, 로트에 포함된 칩의 수와 각 잡 유형에 할당된 로트의 수를 변경해가면서 100개 의 문제데이터를 생성해 학습에 이용하여 시뮬레이션 로그를 생성하였습니다.
  - 해당 디스패쳐의 성능은 AWT(Average Waiting Time)과 AIT(Average Idle Time) 관점에서 측정되었습니다.
- 결과
  - 미리 학습된 모델을 사용하여 간단한 계산만을 시행하기 때문에 기존의 메타휴리스틱 기법들보다 빠르게 로트 디스패치 룰을 선택할 수 있습니다.
  - 제안된 방법이 AWT와 AIT측면에서 모두 압도하는 결과를 내진 않았지만, 평균적으로 기존의 단일 디스패치 규칙보다 좋은 성능을 보였습니다.
  - 목적함수의 가중치를 조정하면 상황에 따른 최적의 성능을 보여줄 수 있습니다.
  - 의사결정 시점에 적합한 디스패치 규칙을 선택하기 때문에 사용자 입장에서 로트가 설비에 할당되는 이유에 대해 이해하기 용이합니다. 

## :open_file_folder: 차후 연구방향이나 보완점은 무엇입니까?
- 고도화를 위해 선택의 보상을 최대회하는 방향으로 강화학습을 적용할 수 있습니다.
- 본 RSD의 액션 벡터를 표현하는 디스패치 규칙들은 차후 강화학습의 액션 공간의 정의로 사용될 수 있습니다.

## :thumbsup: novelty와 논문을 통해 배운 것은 무엇입니까?
- 기존에 제안되었던 ANN 기반 디스패쳐(본문 LDO)보다 성능이 좋았으며, 부족한 설명력을 확보할 수 있었습니다.
- 스케쥴링이 정말 복잡한 문제라는 것을 다시 한번 깨달았습니다.
- 지도학습이 어떻게 활용될 수 있는지 볼 수 있었습니다.
- 현실의 문제를 DL으로 접근할 때, 어떤 방식으로 입력벡터가 디자인되어야 할지 고민해볼 수 있었습니다.

## :loop: 궁금한 점이나 추가로 읽으면 좋은 레퍼런스가 있습니까?
추가적으로 궁금한 사항에 대해서 적어주세요.
같이 읽으면 좋은 레퍼런스의 제목과 URL을 덧붙혀주세요.

**Comment by nnaeueun** [comment]
**우와 광종쿤 대단해요👍**
